import React from 'react';
import {AbsoluteFill, Audio, Composition, interpolate, Sequence, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import receipt from '../../evidence/canonical-run.json' with {type: 'json'};
import './video.css';

const C = {mint:'#ACEED1', ink:'#073D31', paper:'#FCFEFC', red:'#AC263D', green:'#096747'};
const mono = {fontFamily:'ui-monospace, SFMono-Regular, Consolas, monospace'};
const narration = staticFile('narration-master.wav');
const capture = (name:string) => staticFile(`live-capture/${name}.png`);

function Frame({children, eyebrow='CONTINUITY DESK', tone=C.ink, captureName}:{children:React.ReactNode;eyebrow?:string;tone?:string;captureName?:string}){
 const f=useCurrentFrame(); return <AbsoluteFill style={{background:C.mint,color:tone,padding:70}}>{captureName&&<img className="live-capture" src={capture(captureName)} />}<div className="top"><span className="wordmark">CALLSHEET ZERO</span><span className="eyebrow">{eyebrow}</span><span style={mono as any}>REV {f<150?'—':'01'}</span></div>{children}<div className="footer">CONCURRENT CONSTRAINT REPAIR · VERIFIED EVIDENCE WALKTHROUGH</div></AbsoluteFill>
}
function Title({text,sub}:{text:string;sub?:string}){return <div className="title"><h1>{text}</h1>{sub&&<p>{sub}</p>}</div>}
function Card({children,red=false,green=false}:{children:React.ReactNode;red?:boolean;green?:boolean}){return <div className={'card '+(red?'red ':'')+(green?'green':'')}>{children}</div>}
function Desk(){return <Frame captureName="01-landing"><Title text="Three agents can all be right locally — and still produce an impossible shoot."/><div className="incident"><div><span className="eyebrow">PRODUCTION DISRUPTION</span><h2>Weather hold</h2><p>Courtyard exterior</p></div><div className="delay">Lead actor<br/><b>+90 min delay</b></div></div><div className="agents">{receipt.concurrency.agents.map((a)=><Card key={a}><span className="eyebrow">CONCURRENT</span><h3>{a}</h3><div className="pulse"/></Card>)}</div></Frame>}
function Concurrency(){return <Frame eyebrow="VERIFIED REPLAY" captureName="replay-1"><Title text="The shared runtime makes the overlap inspectable."/><div className="proof"><span className="eyebrow">ALL 3 STARTED BEFORE FIRST COMPLETION</span><strong>{(receipt.concurrency.threeWayOverlapMs/1000).toFixed(3)}s</strong><small>VERIFIED OVERLAP · captured live evidence</small></div><div className="flow">Production disruption <b>↓</b> Mozaik shared runtime <b>↓</b> model answers <b>↓</b> Deterministic Constraint Guard</div></Frame>}
function Refusal(){return <Frame eyebrow="REV 01 · VERIFIED REPLAY" captureName="replay-2"><Title text="The combined schedule is impossible."/><div className="revision"><div><span className="eyebrow">REV 01</span><h2 className="refuse">COMMIT REFUSED</h2><p>Deterministic decision-layer interpretation of verified hard conflicts.</p></div><div className="conflicts">{receipt.revision01.conflicts.map((x)=><div className="conflict" key={x.resource}><b>{x.resource}</b><span>{x.left} ↔ {x.right}</span></div>)}</div></div><div className="repair">repair.requested <b>↓</b> Schedule Agent only</div></Frame>}
function Repair(){return <Frame eyebrow="TARGETED REPAIR · VERIFIED REPLAY" captureName="replay-3"><Title text="Only what changed gets repaired."/><div className="dimrow"><Card><span className="eyebrow">HELD</span><h3>Talent Agent</h3></Card><Card><span className="eyebrow">HELD</span><h3>Logistics Agent</h3></Card><Card green><span className="eyebrow">ACTIVE</span><h3>Schedule Agent</h3></Card></div><div className="change"><span className="eyebrow">SCENE REVISION</span><strong>S22</strong><div className="times">16:30 <b>→</b> 18:00</div></div></Frame>}
function Allowed(){return <Frame eyebrow="REV 02 · VERIFIED REPLAY" captureName="replay-5"><Title text="The repaired call sheet clears the guard."/><div className="revision allowed"><div><span className="eyebrow">REV 02</span><h2 className="allow">COMMIT ALLOWED</h2></div><div className="bigzero">0 <small>FINAL CONFLICTS</small></div></div><div className="receiptline">deterministicFallbackUsed = false</div></Frame>}
function Modes(){return <Frame eyebrow="TRUTH BOUNDARY" captureName="03-live-result"><Title text="Know what is live. Know what is replay."/><div className="modes"><Card><span className="eyebrow">RUN LIVE</span><h2>Fresh stochastic Mozaik execution</h2><p>Outcome may differ</p></Card><Card green><span className="eyebrow">VERIFIED REPLAY</span><h2>Captured canonical live evidence</h2><p>No new model call</p></Card></div><div className="receiptbox">evidence/canonical-run.json<br/><br/>threeWayOverlapMs: 8432<br/>conflictCount: 3<br/>repair.target: Schedule Agent<br/>revision02.finalConflictCount: 0</div></Frame>}
function Adaption(){return <Frame eyebrow="SECONDARY ASYNCHRONOUS LAYER" captureName="09-adaption"><Title text="Verified repair can become preference data."/><div className="adaption"><div>VERIFIED REPAIR</div><b>↓</b><div>ADAPTION LABS</div><b>↓</b><div>preference_pairs<br/><small>chosen + rejected</small></div></div><p className="boundary">ASYNCHRONOUS · NOT IN RUN LIVE<br/>Constraint Guard remains safety authority</p></Frame>}
function Closing(){return <Frame eyebrow="CONTINUITY DESK"><div className="closing"><span className="eyebrow">THE MEMORY HOOK</span><h1>Parallel decisions are easy.</h1><h2>CALLSHEET ZERO refuses the collisions they create — and repairs only what changed.</h2><div className="brand">CALLSHEET ZERO</div><p>Concurrent constraint repair for a world that won't wait.</p><small>callsheet-zero.vercel.app</small></div></Frame>}
export const Video=()=> <AbsoluteFill><Audio src={narration}/><Sequence from={0} durationInFrames={180}><Desk/></Sequence><Sequence from={180} durationInFrames={300}><Concurrency/></Sequence><Sequence from={480} durationInFrames={390}><Refusal/></Sequence><Sequence from={870} durationInFrames={300}><Repair/></Sequence><Sequence from={1170} durationInFrames={330}><Allowed/></Sequence><Sequence from={1500} durationInFrames={360}><Modes/></Sequence><Sequence from={1860} durationInFrames={360}><Adaption/></Sequence><Sequence from={2220} durationInFrames={630}><Closing/></Sequence></AbsoluteFill>;
export const RemotionRoot=()=> <Composition id="CallsheetZeroDemo" component={Video} durationInFrames={2850} fps={30} width={1920} height={1080}/>;




